### ISSUE TITLE
Build errors: chroot: failed to run command ‘/bin/bash’: Exec format error; No such file or directory

### ISSUE THREAD

**Issue by bofm** [igorpecovnik/Cubietruck-Debian#40]
Following the `DIY` section of `README`, I get the errors:
```
...
------ Install board specific applications
head: cannot open ‘/home/vagrant/Cubietruck-Debian/output/output/sdcard/etc/rc.local’ for reading: No such file or directory
chroot: failed to run command ‘/bin/bash’: Exec format error
cp: cannot stat ‘/home/vagrant/Cubietruck-Debian/output/sunxi-tools/fex2bin’: No such file or directory
cp: cannot stat ‘/home/vagrant/Cubietruck-Debian/output/sunxi-tools/bin2fex’: No such file or directory
cp: cannot stat ‘/home/vagrant/Cubietruck-Debian/output/sunxi-tools/nand-part’: No such file or directory
cp: cannot create regular file ‘/home/vagrant/Cubietruck-Debian/output/output/sdcard/usr/local/bin/brcm_patchram_plus’: No such file or directory
chroot: failed to run command ‘/bin/bash’: Exec format error
chroot: failed to run command ‘/bin/bash’: Exec format error
sed: can't read /home/vagrant/Cubietruck-Debian/output/output/sdcard/etc/lirc/hardware.conf: No such file or directory
sed: can't read /home/vagrant/Cubietruck-Debian/output/output/sdcard/etc/lirc/hardware.conf: No such file or directory
sed: can't read /home/vagrant/Cubietruck-Debian/output/output/sdcard/etc/lirc/hardware.conf: No such file or directory
sed: can't read /home/vagrant/Cubietruck-Debian/output/output/sdcard/etc/lirc/hardware.conf: No such file or directory
sed: can't read /home/vagrant/Cubietruck-Debian/output/output/sdcard/etc/lirc/hardware.conf: No such file or directory
cp: cannot create regular file ‘/home/vagrant/Cubietruck-Debian/output/output/sdcard/etc/lirc/lircd.conf’: No such file or directory
------ done.
------ Install kernel
sed: can't read /home/vagrant/Cubietruck-Debian/output/output/sdcard/etc/init.d/cpufrequtils: No such file or directory
sed: can't read /home/vagrant/Cubietruck-Debian/output/output/sdcard/etc/init.d/cpufrequtils: No such file or directory
sed: can't read /home/vagrant/Cubietruck-Debian/output/output/sdcard/etc/init.d/cpufrequtils: No such file or directory
chroot: failed to run command ‘/bin/bash’: Exec format error
------ Compile headers scripts
chroot: failed to run command ‘/bin/bash’: Exec format error
/home/vagrant/Cubietruck-Debian/lib/boards.sh: line 191: mkimage: command not found
Archive:  /home/vagrant/Cubietruck-Debian/lib/bin/linux-firmware.zip
   creating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/brcm/
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/brcm/bcm4330.hcd
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/brcm/bcm4329.hcd
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/brcm/brcmfmac4329-sdio.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/brcm/brcmfmac4329-sdio.txt
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/brcm/brcmfmac4330-sdio.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/brcm/brcmfmac4330-sdio.txt
   creating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8188efw.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8188eufw.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8192cfw.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8192cfwU_B.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8192cfwU.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8192cufw_A.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8192cufw_B.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8192cufw.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8192cufw_TMSC.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8192defw.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8192eefw.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8192sefw.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8712u.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8723aufw_A.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8723aufw_B.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8723aufw_B_NoBT.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8723befw.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8723fw_B.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8723fw.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8821aefw.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rtlwifi/rtl8821aefw_wowlan.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/iwlwifi-7260-7.ucode
   creating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/intel/
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/intel/ibt-hw-37.7.bseq
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/intel/ibt-hw-37.7.10-fw-1.0.2.3.d.bseq
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/intel/ibt-hw-37.7.10-fw-1.80.1.2d.d.bseq
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/intel/ibt-hw-37.7.10-fw-1.80.2.3.d.bseq
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/intel/ibt-hw-37.8.bseq
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/intel/ibt-hw-37.8.10-fw-1.10.2.27.d.bseq
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/rt2870.bin
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/iwlwifi-7260-9.ucode
  inflating: /home/vagrant/Cubietruck-Debian/output/output/sdcard/lib/firmware/iwlwifi-7260-8.ucode
------ Saving build summary to the image
/home/vagrant/Cubietruck-Debian/output/output/sdcard/root/readme.txt
------ Closing image
chroot: failed to run command ‘/bin/bash’: Exec format error
rm: cannot remove ‘/home/vagrant/Cubietruck-Debian/output/output/sdcard/usr/bin/qemu-arm-static’: No such file or directory
dd: failed to open ‘u-boot-sunxi-with-spl.bin’: No such file or directory
  adding: Cubietruck_Debian_3.1_wheezy_...md5 (stored 0%)
  adding: Cubietruck_Debian_3.1_wheezy_...raw (deflated 92%)
  adding: readme.txt (deflated 62%)
  adding: imagewriter.exe (deflated 36%)
  adding: imagewriter.md5 (stored 0%)
Runtime 22 min.
```

This is what I have in the end.
```bash
root@vagrant-ubuntu-trusty-64:~/Cubietruck-Debian/output/output# find -type f -exec du -sh {} \;
91M     ./Cubietruck_Debian_3.1_wheezy_...zip
90M     ./rootfs/wheezy.raw.gz
12K     ./kernel/..-cubietruck-default.tar
4.0K    ./u-boot/cubietruck_default_u-boot_...tgz
```

**Comment by ownedcore** [comment]
Seems like you have some problem with qemu-arm-static
"rm: cannot remove ‘/home/vagrant/Cubietruck-Debian/output/output/sdcard/usr/bin/qemu-arm-static’: No such file or directory"
Guess a "apt-get install qemu-user-static" should fix it

**Comment by kenhys** [comment]
I've encounted similar problem, then I did "sudo apt-get install qemu" to fix it.

**Comment by bofm** [comment]
@ownedcore shouldn't we start investigating errors from the first one? Anyway, installing qemu didn't help. The errors remain.

**Comment by kenhys** [comment]
@bofm  after installing qemu packages, did you remove output/output directory?

**Comment by bofm** [comment]
@kenhys Yes, I did. Here is the [full output](https://dl.dropboxusercontent.com/u/21373460/out.txt) if somebody is interested.

**Comment by kenhys** [comment]
It seems that output/linux-sunxi is broken.

**Comment by igorpecovnik** [comment]
Issue resolved.
